### ISSUE TITLE
cc1plus build error

### ISSUE THREAD

**Issue by qw8z5fUB** [GREAT-WHU/gv_tools#3]
Hi there, thanks for open-sourcing this, I'm looking forward to trying it out.

When I try build for melodic/bionic or noetic/focal, I get the error:

`cc1plus: error: to generate dependencies you must specify either -M or -MM`

This happens both with `catkin_make` and `catkin build`.

Are you able to help me debug this? When you build for ROS, which ROS and linux version are you using?

**Comment by qw8z5fUB** [comment]
Follow up, I've confirmed I can build in focal/noetic with the following diff applied:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3d7c418..74ca6aa 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -3,8 +3,7 @@ cmake_minimum_required(VERSION 2.8.12)
 # Project name
 project(gv_tools)
 
-set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -MP")
-add_compile_options(-MP)
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")^M
 
 add_definitions(-DGLOG_NO_ABBREVIATED_SEVERITIES)
 add_definitions(-DNOMINMAX)
 ```

I'm not familiar with the `-MP` flag - can it be removed?

**Comment by yuxuanzhou97** [comment]
Thanks for the feedback! I believe this "-MP" can be removed.

**Comment by qw8z5fUB** [comment]
Great, I see you've updated the CMakeLists.txt already. Thanks for the quick fix!
